#$Id: Makefile,v 1.1 2007-06-30 12:41:42 kbk Exp $
#
# Makefile for making 'meteo.nc' forcing for - upwelling- setup.
#
#

meteo.nc: meteo.cdl
	ncgen -b meteo.cdl

#-----------------------------------------------------------------------
# Copyright (C) 2007 - Karsten Bolding and Hans Burchard (BBH)         !
#-----------------------------------------------------------------------
