#$Id: Makefile,v 1.1 2007-06-27 12:38:06 kbk Exp $
#
# Makefile for making STATIC version of the - box_curvilinear - executable.
#

SHELL	= /bin/sh

name	= box_curvilinear
setup	= $(name)

include ../Rules.make

#export GETM_PARALLEL=true

STATIC += -DCURVILINEAR
#STATIC += -DINCLUDE_HALOS

input:


#-----------------------------------------------------------------------
# Copyright (C) 2006 - Lars Unmlauf and Karsten Bolding                !
#-----------------------------------------------------------------------
