#
# Makefile for making STATIC version of the - box_spherical - executable.
#

SHELL	= /bin/sh

name	= box_spherical
setup	= $(name)

include ../Rules.make

STATIC += -DUV_TVD -DSPHERICAL

include ../Boxes.make

#-----------------------------------------------------------------------
# Copyright (C) 2006 - Lars Unmlauf and Karsten Bolding                !
#-----------------------------------------------------------------------
