#$Id: Makefile,v 1.1 2007-06-27 12:38:06 kbk Exp $
#
# Makefile for making STATIC version of the - box_spherical - executable.
#

SHELL	= /bin/sh

name	= box_spherical
setup	= $(name)

include ../Rules.make

STATIC += -DSPHERICAL

input:


#-----------------------------------------------------------------------
# Copyright (C) 2006 - Lars Unmlauf and Karsten Bolding                !
#-----------------------------------------------------------------------
