#
# Makefile for making STATIC version of the - haidvogel - executable
#

SHELL	  = /bin/bash

name	  = haidvogel
setup	  = $(name)

STATIC += -DNO_BOTTFRIC -DUV_TVD

include ../Rules.make

input:

$(name)_clean:

.PHONY: input
