#
# Makefile for making STATIC version of the - haidvogel - executable
#

SHELL	  = /bin/sh

name	  = haidvogel
setup	  = $(name)

STATIC += -DSTATIC -DNO_BOTTFRIC

include ../Rules.make

.PHONY: input
input:

$(name)_clean:
